function execute() {
    return Response.success([
        {title: "Adult", input: "https://hentai2read.com/hentai-list/category/Adult/all/last-updated", script: "gen.js"},
        {title: "Anal", input: "https://hentai2read.com/hentai-list/category/Anal/all/last-updated", script: "gen.js"},
        {title: "Big Breasts", input: "https://hentai2read.com/hentai-list/category/Big%20Breasts/all/last-updated", script: "gen.js"},
        {title: "Comedy", input: "https://hentai2read.com/hentai-list/category/Comedy/all/last-updated", script: "gen.js"},
        {title: "Compilation", input: "https://hentai2read.com/hentai-list/category/Compilation/all/last-updated", script: "gen.js"},
        {title: "Doujinshi", input: "https://hentai2read.com/hentai-list/category/Doujinshi/all/last-updated", script: "gen.js"},
        {title: "Ecchi", input: "https://hentai2read.com/hentai-list/category/Ecchi/all/last-updated", script: "gen.js"},
        {title: "Futanari", input: "https://hentai2read.com/hentai-list/category/Futanari/all/last-updated", script: "gen.js"},
        {title: "Harem", input: "https://hentai2read.com/hentai-list/category/Harem/all/last-updated", script: "gen.js"},
        {title: "Incest", input: "https://hentai2read.com/hentai-list/category/Incest/all/last-updated", script: "gen.js"},
        {title: "Lactation", input: "https://hentai2read.com/hentai-list/category/Lactation/all/last-updated", script: "gen.js"},
        {title: "Licensed", input: "https://hentai2read.com/hentai-list/category/Licensed/all/last-updated", script: "gen.js"},
        {title: "Masturbation", input: "https://hentai2read.com/hentai-list/category/Masturbation/all/last-updated", script: "gen.js"},
        {title: "Oneshot", input: "https://hentai2read.com/hentai-list/category/Oneshot/all/last-updated", script: "gen.js"},
        {title: "Rape", input: "https://hentai2read.com/hentai-list/category/Rape/all/last-updated", script: "gen.js"},
        {title: "Robotics", input: "https://hentai2read.com/hentai-list/category/Robotics/all/last-updated", script: "gen.js"},
        {title: "Romance", input: "https://hentai2read.com/hentai-list/category/Romance/all/last-updated", script: "gen.js"},
        {title: "School Life", input: "https://hentai2read.com/hentai-list/category/School%20Life/all/last-updated", script: "gen.js"},
        {title: "Serialized", input: "https://hentai2read.com/hentai-list/category/Serialized/all/last-updated", script: "gen.js"},
        {title: "Shotacon", input: "https://hentai2read.com/hentai-list/category/Shotacon/all/last-updated", script: "gen.js"},
        {title: "Tentacles", input: "https://hentai2read.com/hentai-list/category/Tentacles/all/last-updated", script: "gen.js"},
        {title: "Tragedy", input: "https://hentai2read.com/hentai-list/category/Tragedy/all/last-updated", script: "gen.js"},
        {title: "Un-censored", input: "https://hentai2read.com/hentai-list/category/Un-censored/all/last-updated", script: "gen.js"},
        {title: "Yaoi", input: "https://hentai2read.com/hentai-list/category/Yaoi/all/last-updated", script: "gen.js"},
        {title: "Yuri", input: "https://hentai2read.com/hentai-list/category/Yuri/all/last-updated", script: "gen.js"},
    ]);
}